from biked_commons.bike_embedding.clip_embedding_calculator import ClipEmbeddingCalculatorImpl
from biked_commons.api.rendering import SingleThreadedRenderer

EMBEDDING_CALCULATOR = ClipEmbeddingCalculatorImpl()
IMAGE_CONVERTOR = SingleThreadedRenderer()
