name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-backend:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt;
      - name: Install backend
        run: pip install .;
      - name: run tests
        run: python3 -m unittest discover -v;
